<?php

namespace Database\Seeders;

use App\Models\Requirement;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class RequirementSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $requirements = [
            'Color copy of CNIC',
            'Latest paid electricity bill',
            'Phone Number',
            'Email address',
            'Rent agreement/ownership docs of Office premises',
            'Letterhead',
            'Partnership Deed',
            'Partnership registration certificate',
            'Authorization of principal Officer',
            "Color copy of CNIC's of Partners",
            'Rent agreement/ownership docs of Office premises',
            'Incorporation Certificate',
            'Memorandum & Articles of Association',
            'NTN of all members',
            'Constitution of NPO',
            'Registration Certificate',
            'Any other document as required by the concerned authority',
            'Details of Taxes deducted at source during each quarter',
            'Other information as required',
            'Annual Salary certificate',
            'Other Income sources if any',
            'Annual personal expense',
            'Details of all owned assets',
            'Disposals during the year',
            'Investments during the year',
            'Other inflows/outflows during the year',
            'Other information as required',
            'Annual Accounts',
            'Annual Audited Accounts',
            'Taxes deducted at source',
            'Color copy of CNIC',
            'Latest paid electricity bill',
            'Phone Number',
            'Email address',
            'Rent agreement/ownership docs of Office premises',
            'Letterhead',
            'Partnership Deed',
            'Partnership registration certificate',
            'Authorization of principal Officer',
            'Color copy of CNIC',
            'Latest paid electricity bill',
            'Phone Number',
            'Email address',
            'Rent agreement/ownership docs of Office premises',
            'Letterhead',
            'Partnership Deed',
            'Partnership registration certificate',
            'Authorization of principal Officer',
            'Incorporation Certificate',
            'Memorandum & Articles of Association',
            'Color copy of CNIC',
            'Latest paid electricity bill',
            'Phone Number',
            'Email address',
            'Authorization of principal Officer',
            'Letterhead',
            'Rent agreement/ownership docs of Office premises',
            'Constitution of NPO',
            'Incorporation Certificate',
            'Any other document as required by the concerned authority',
            'NTN of all members',
            'Details of Taxes deducted at source during each quarter',
            'Other information as required',
            'Annual Salary certificates',
            'Other Income sources if any',
            'Annual personal expense',
            'Details of all owned assets',
            'Investments during the year',
            'Disposals during the year',
            'Other inflows/outflows during the year',
            'Other information as required',
            'Annual Accounts',
            'Other Income sources if any',
            'Annual personal expense',
            'Details of all owned assets',
            'Investments during the year',
            'Disposals during the year',
            'Other inflows/outflows during the year',
            'Other information as required',
            'Annual Accounts',
            'Taxes deducted at source',
            'Other information as required',
            'Bank Account Certificate',
            'Acquisition Date, Capacity and Business Activity',
            'Particulars of all branches (if any)',
            'Authorization of principal Officer',
            'GPS-tagged photographs of the business premises',
            'Consumer number with the gas and electricity supplier along with pictures of utilities meter',
            'GPS-tagged photographs of machinery and industrial electricity or gas meter installed (Manufacturer only)',
            'Color copy of CNICs of Partners',
            'Rent agreement/ownership docs of Office premises',
            'Latest paid electricity bill',
            'Biometric Verification',
            'Post Verification (Manufacturer only)',
            'Copies of Sales Invoices',
            'Copies of Purchse Invoices',
            'Bank Statements',
            'Other Information As Required',
            'Colored Copy of CNIC',
            'Rent agreement/ownership docs of Office premises',
            'Letterhead',
            'Latest Electricity Bill',
            'Phone Number',
            'Email Address',
            'Bank Account Certificate',
            'Acquisition Date, Capacity & Business Activity',
            'Particulars of all branches (if applicable)',
            'Autorization of Principal Officer',
            'Signed Application Form',
            'Incorporation Certificate',
            'Memorandum of Association',
            'Articles of Association',
            'Incorporation form A & 29',
            'Colored Copy of CNIC',
            'Rent agreement/ownership docs of Office premises',
            'Letterhead',
            'Latest Electricity Bill',
            'Phone Number',
            'Email Address',
            'Bank Account Certificate',
            'Acquisition Date, Capacity & Business Activity',
            'Particulars of all branches (if applicable)',
            'Autorization of Principal Officer',
            'Signed Application Form',
            'Partnership Certificate',
            'Partnership Deed',
            'Colored Copy of CNIC',
            'Rent agreement/ownership docs of Office premises',
            'Letterhead',
            'Latest Electricity Bill',
            'Phone Number',
            'Email Address',
            'Bank Account Certificate',
            'Acquisition Date, Capacity & Business Activity',
            'Particulars of all branches (if applicable)',
            'Autorization of Principal Officer',
            'Signed Application Form',
            'Three Names of the proposed company',
            'Neat and Clear Scanned copies of CNICs of all the proposed Directors / subscribers',
            'NTN of the proposed directors / subscribers',
            'Registered address / correspondence address of the proposed Company',
            'The principal business of the proposed company',
            'Nature of the business activity',
            'Authorized Capital Value',
            'Paid up Capital',
            'Value per share e.g.Rs. 10, Rs. 50 or Rs. 100 etc',
            'Combination of Shares agreed to be subscribed by each director / subscriber',
            'Name of the Chief Executive of the Proposed Company',
            'Authorization from other subscribers. (For Offline only)',
            'Telephone numbers and email ID of all the proposed directors',
            'Telephone numbers and email ID of all the proposed directors of the Company',
            'Name of declarant person',
            'SECP login details of the proposed directors / subscribers(if any)',
            'Three Names of the proposed company',
            'Neat and Clear Scanned copies of CNICs of all the proposed Directors / subscribers',
            'NTN of the proposed directors / subscribers',
            'Registered address / correspondence address of the proposed Company',
            'The principal business of the proposed company',
            'Nature of the business activity',
            'Authorized Capital Value',
            'Paid up Capital',
            'Value per share e.g.Rs. 10, Rs. 50 or Rs. 100 etc',
            'Name of the Chief Executive of the Proposed Company',
            'Telephone numbers and email ID of all the proposed directors',
            'Telephone numbers and email ID of all the proposed directors of the Company',
            'Name of declarant person',
            'SECP login details of the proposed directors / subscribers(if any)',
            'Three Names of the proposed company',
            'Neat and Clear Scanned copies of CNICs of all the proposed Directors / subscribers',
            'NTN of the proposed directors / subscribers',
            'Registered address / correspondence address of the proposed Company',
            'The principal business of the proposed company',
            'Nature of the business activity',
            'Authorized Capital Value',
            'Paid up Capital',
            'Value per share e.g.Rs. 10, Rs. 50 or Rs. 100 etc',
            'Combination of Shares agreed to be subscribed by each director / subscriber',
            'Name of the Chief Executive of the Proposed Company',
            'Authorization from other subscribers. (For Offline only)',
            'Telephone numbers and email ID of all the proposed directors',
            'Telephone numbers and email ID of all the proposed directors of the Company',
            'Name of declarant person',
            'SECP login details of the proposed directors / subscribers(if any)',
            'Partnership Deed',
            'Signed Partnership Form',
            'Authorization of principal officer',
            'Color Copy of CNICs of partners',
            'Rent Agreement and Ownership Documents of Office Premises',
            'Letterhead',
            'Latest Paid Electricity Bill',
            'Phone Number',
            'Email Address',
            'Memorandum and articles of Association',
            'Authorization of principal officer',
            'Color Copy of CNICs of partners',
            'Rent Agreement and Ownership Documents of Office Premises',
            'Letterhead',
            'Latest Paid Electricity Bill',
            'Phone Number',
            'Email Address',
            'NOC from Home Department',
            'TM-1 in duplicates',
            'Six representations affixed on a durable paper of 13x8 inch',
            'CNIC of the Trademark Holder/partners',
            'Specification of goods or services sought to be protected in any class',
            'Residential address of holder or Letterhead of the Business',
            'Other Information or Documents as required',
            'Two Copies of Work',
            'Demand Draft / Pay order of fee as applicable per work',
            'CNIC of the Copyrights Holder / partners',
            'NOC from publisher if work has been published and publisher is different from applicant',
            'Search certificate from trademark Office if the work is capable of being used on goods',
            'Residential address of holder or Letterhead of the Business',
            'Power of attorney',
            'Other Information or Documents as required',
            'Form P - 1 or Form P - 1A application without priority',
            'Form P - 2 or Form P - 2A application with priority',
            'Form P - 3 for provisional or Form P - 3A for complete specification',
            'Patent Specification',
            'Drawings, if any',
            'Demand Draft / Pay order of fee as applicable per work ',
            'Form P - 28 - power of Attorney - if any',
            'Priority document - for conventional applications - ',
            'CNIC of the Copyrights applicant',
            'Other Information or Documents as required',
        ];

        foreach(array_unique($requirements) as $requirement) {
            Requirement::create([
                'title' => $requirement
            ]);
        }
    }
}
